## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("Fuji", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Fuji")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
matrix:
  allow_failures:
    - julia: nightly
